# Generated by Django 5.0.3 on 2024-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuteRole',
            fields=[
                ('guild_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('role_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
